### ISSUE TITLE
can't get started (seed and db setup)

### ISSUE THREAD

**Issue by linkwoman** [toptal/chewy_example#6]
Hi there.  I can't seem to get this started.   I have an es installation, so I changed host in chewy.yml from 9250 to 9200 but that didn't fix the problem.

I've tried just rake db:setup and the following command that your readme says to use, and I get the same thing every time.

Chewy::UndefinedUpdateStrategy: Index update strategy is undefined in current context. Please wrap your code with Chewy.strategy(:strategy_name) block.

help!

$ RAILS_ENV=test rake db:setup && rake spec
-- create_table("books", {:force=>true})
   -> 0.0331s
-- create_table("dudes", {:force=>true})
   -> 0.0013s
-- create_table("taggings", {:force=>true})
   -> 0.0016s
-- add_index("taggings", ["tag_id", "taggable_id", "taggable_type", "context", "tagger_id", "tagger_type"], {:name=>"taggings_idx", :unique=>true})
   -> 0.0010s
-- create_table("tags", {:force=>true})
   -> 0.0010s
-- add_index("tags", ["name"], {:name=>"index_tags_on_name", :unique=>true})
   -> 0.0008s
-- create_table("videos", {:force=>true})
   -> 0.0011s
-- initialize_schema_migrations_table()
   -> 0.0028s
rake aborted!
*Chewy::UndefinedUpdateStrategy: Index update strategy is undefined in current context.
Please wrap your code with `Chewy.strategy(:strategy_name) block.`*
/Users/darby/.rvm/gems/ruby-2.0.0-p0/bundler/gems/chewy-7f38c5a094c6/lib/chewy/strategy/base.rb:17:in `update'
/Users/darby/.rvm/gems/ruby-2.0.0-p0/bundler/gems/chewy-7f38c5a094c6/lib/chewy/type/observe.rb:54:in `update_index'
/Users/darby/.rvm/gems/ruby-2.0.0-p0/bundler/gems/chewy-7f38c5a094c6/lib/chewy/type/observe.rb:44:in `block in update_index'
/Users/darby/.rvm/gems/ruby-2.0.0-p0/gems/activesupport-4.0.2/lib/active_support/callbacks.rb:394:in `_run__3044157516336772284__save__callbacks'
/Users/darby/.rvm/gems/ruby-2.0.0-p0/gems/activesupport-4.0.2/lib/active_support/callbacks.rb:80:in `run_callbacks'
/Users/darby/.rvm/gems/ruby-2.0.0-p0/gems/activerecord-4.0.2/lib/active_record/callbacks.rb:302:in `create_or_update'
/Users/darby/.rvm/gems/ruby-2.0.0-p0/gems/activerecord-4.0.2/lib/active_record/persistence.rb:128:in `save!'
/Users/darby/.rvm/gems/ruby-2.0.0-p0/gems/activerecord-4.0.2/lib/active_record/validations.rb:57:in `save!'
/Users/darby/.rvm/gems/ruby-2.0.0-p0/gems/activerecord-4.0.2/lib/active_record/attribute_methods/dirty.rb:41:in `save!'
/Users/darby/.rvm/gems/ruby-2.0.0-p0/gems/activerecord-4.0.2/lib/active_record/transactions.rb:275:in `block in save!'
/Users/darby/.rvm/gems/ruby-2.0.0-p0/gems/activerecord-4.0.2/lib/active_record/transactions.rb:326:in `block in with_transaction_returning_status'
/Users/darby/.rvm/gems/ruby-2.0.0-p0/gems/activerecord-4.0.2/lib/active_record/connection_adapters/abstract/database_statements.rb:202:in `block in transaction'
/Users/darby/.rvm/gems/ruby-2.0.0-p0/gems/activerecord-4.0.2/lib/active_record/connection_adapters/abstract/database_statements.rb:210:in `within_new_transaction'
/Users/darby/.rvm/gems/ruby-2.0.0-p0/gems/activerecord-4.0.2/lib/active_record/connection_adapters/abstract/database_statements.rb:202:in `transaction'
/Users/darby/.rvm/gems/ruby-2.0.0-p0/gems/activerecord-4.0.2/lib/active_record/transactions.rb:209:in `transaction'
/Users/darby/.rvm/gems/ruby-2.0.0-p0/gems/activerecord-4.0.2/lib/active_record/transactions.rb:323:in `with_transaction_returning_status'
/Users/darby/.rvm/gems/ruby-2.0.0-p0/gems/activerecord-4.0.2/lib/active_record/transactions.rb:275:in `save!'
/Users/darby/.rvm/gems/ruby-2.0.0-p0/gems/factory_girl-4.5.0/lib/factory_girl/configuration.rb:14:in `block in initialize'
/Users/darby/.rvm/gems/ruby-2.0.0-p0/gems/factory_girl-4.5.0/lib/factory_girl/evaluation.rb:15:in `[]'
/Users/darby/.rvm/gems/ruby-2.0.0-p0/gems/factory_girl-4.5.0/lib/factory_girl/evaluation.rb:15:in `create'
/Users/darby/.rvm/gems/ruby-2.0.0-p0/gems/factory_girl-4.5.0/lib/factory_girl/strategy/create.rb:12:in `block in result'
/Users/darby/.rvm/gems/ruby-2.0.0-p0/gems/factory_girl-4.5.0/lib/factory_girl/strategy/create.rb:9:in `tap'
/Users/darby/.rvm/gems/ruby-2.0.0-p0/gems/factory_girl-4.5.0/lib/factory_girl/strategy/create.rb:9:in `result'
/Users/darby/.rvm/gems/ruby-2.0.0-p0/gems/factory_girl-4.5.0/lib/factory_girl/factory.rb:42:in `run'
/Users/darby/.rvm/gems/ruby-2.0.0-p0/gems/factory_girl-4.5.0/lib/factory_girl/factory_runner.rb:23:in `block in run'
/Users/darby/.rvm/gems/ruby-2.0.0-p0/gems/activesupport-4.0.2/lib/active_support/notifications.rb:161:in `instrument'
/Users/darby/.rvm/gems/ruby-2.0.0-p0/gems/factory_girl-4.5.0/lib/factory_girl/factory_runner.rb:22:in `run'
/Users/darby/.rvm/gems/ruby-2.0.0-p0/gems/factory_girl-4.5.0/lib/factory_girl/strategy/create.rb:5:in `association'
/Users/darby/.rvm/gems/ruby-2.0.0-p0/gems/factory_girl-4.5.0/lib/factory_girl/evaluator.rb:31:in `association'
/Users/darby/.rvm/gems/ruby-2.0.0-p0/gems/factory_girl-4.5.0/lib/factory_girl/attribute/association.rb:19:in `block in to_proc'
/Users/darby/.rvm/gems/ruby-2.0.0-p0/gems/factory_girl-4.5.0/lib/factory_girl/evaluator.rb:71:in `instance_exec'
/Users/darby/.rvm/gems/ruby-2.0.0-p0/gems/factory_girl-4.5.0/lib/factory_girl/evaluator.rb:71:in `block in define_attribute'
/Users/darby/.rvm/gems/ruby-2.0.0-p0/gems/factory_girl-4.5.0/lib/factory_girl/attribute_assigner.rb:56:in `get'
/Users/darby/.rvm/gems/ruby-2.0.0-p0/gems/factory_girl-4.5.0/lib/factory_girl/attribute_assigner.rb:16:in `block (2 levels) in object'
/Users/darby/.rvm/gems/ruby-2.0.0-p0/gems/factory_girl-4.5.0/lib/factory_girl/attribute_assigner.rb:15:in `each'
/Users/darby/.rvm/gems/ruby-2.0.0-p0/gems/factory_girl-4.5.0/lib/factory_girl/attribute_assigner.rb:15:in `block in object'
/Users/darby/.rvm/gems/ruby-2.0.0-p0/gems/factory_girl-4.5.0/lib/factory_girl/attribute_assigner.rb:14:in `tap'
/Users/darby/.rvm/gems/ruby-2.0.0-p0/gems/factory_girl-4.5.0/lib/factory_girl/attribute_assigner.rb:14:in `object'
/Users/darby/.rvm/gems/ruby-2.0.0-p0/gems/factory_girl-4.5.0/lib/factory_girl/evaluation.rb:12:in `object'
/Users/darby/.rvm/gems/ruby-2.0.0-p0/gems/factory_girl-4.5.0/lib/factory_girl/strategy/create.rb:9:in `result'
/Users/darby/.rvm/gems/ruby-2.0.0-p0/gems/factory_girl-4.5.0/lib/factory_girl/factory.rb:42:in `run'
/Users/darby/.rvm/gems/ruby-2.0.0-p0/gems/factory_girl-4.5.0/lib/factory_girl/factory_runner.rb:23:in `block in run'
/Users/darby/.rvm/gems/ruby-2.0.0-p0/gems/activesupport-4.0.2/lib/active_support/notifications.rb:161:in `instrument'
/Users/darby/.rvm/gems/ruby-2.0.0-p0/gems/factory_girl-4.5.0/lib/factory_girl/factory_runner.rb:22:in `run'
/Users/darby/.rvm/gems/ruby-2.0.0-p0/gems/factory_girl-4.5.0/lib/factory_girl/strategy_syntax_method_registrar.rb:20:in `block in define_singular_strategy_method'
/Users/darby/.rvm/gems/ruby-2.0.0-p0/gems/factory_girl-4.5.0/lib/factory_girl/strategy_syntax_method_registrar.rb:28:in `block (2 levels) in define_list_strategy_method'
/Users/darby/.rvm/gems/ruby-2.0.0-p0/gems/factory_girl-4.5.0/lib/factory_girl/strategy_syntax_method_registrar.rb:28:in `times'
/Users/darby/.rvm/gems/ruby-2.0.0-p0/gems/factory_girl-4.5.0/lib/factory_girl/strategy_syntax_method_registrar.rb:28:in `each'
/Users/darby/.rvm/gems/ruby-2.0.0-p0/gems/factory_girl-4.5.0/lib/factory_girl/strategy_syntax_method_registrar.rb:28:in `map'
/Users/darby/.rvm/gems/ruby-2.0.0-p0/gems/factory_girl-4.5.0/lib/factory_girl/strategy_syntax_method_registrar.rb:28:in `block in define_list_strategy_method'
/Users/darby/_darby/RubymineProjects/chewy_example/db/seeds.rb:9:in `<top (required)>'
/Users/darby/.rvm/gems/ruby-2.0.0-p0/gems/activesupport-4.0.2/lib/active_support/dependencies.rb:223:in `load'
/Users/darby/.rvm/gems/ruby-2.0.0-p0/gems/activesupport-4.0.2/lib/active_support/dependencies.rb:223:in `block in load'
/Users/darby/.rvm/gems/ruby-2.0.0-p0/gems/activesupport-4.0.2/lib/active_support/dependencies.rb:214:in `load_dependency'
/Users/darby/.rvm/gems/ruby-2.0.0-p0/gems/activesupport-4.0.2/lib/active_support/dependencies.rb:223:in `load'
/Users/darby/.rvm/gems/ruby-2.0.0-p0/gems/railties-4.0.2/lib/rails/engine.rb:540:in `load_seed'
/Users/darby/.rvm/gems/ruby-2.0.0-p0/gems/activerecord-4.0.2/lib/active_record/tasks/database_tasks.rb:154:in `load_seed'
/Users/darby/.rvm/gems/ruby-2.0.0-p0/gems/activerecord-4.0.2/lib/active_record/railties/databases.rake:181:in `block (2 levels) in <top (required)>'
/Users/darby/.rvm/gems/ruby-2.0.0-p0/bin/ruby_noexec_wrapper:14:in `eval'
/Users/darby/.rvm/gems/ruby-2.0.0-p0/bin/ruby_noexec_wrapper:14:in `<main>'
Tasks: TOP => db:setup => db:seed

**Comment by pyromaniac** [comment]
Hello. You haven't change chewy.yml because rake elasticsearch:start is supposed to start ES node on 9250. And it is working. The exception have been raised during data seeding, I forgot to wrap it with strategy unfortunately. Currently this is fixed, so feel free to grab the latest master and continue your experiments.

**Comment by linkwoman** [comment]
cool, will try.  thanks. :-)

**Comment by linkwoman** [comment]
Ok.  I put it back to 9250, pulled.  Had to change source 'https://rubygems.org' to source 'http://rubygems.org' BTW to get gems loaded due to a certificate error.

Couldn't get this line to run:
RAILS_ENV=test rake elasticsearch:start db:setup && rake spec

Was able to get rake db:setup to run and started rails. I'm able to query my elasticsearch instance, which is my old instance, still running on 9200, now with new indexes entertainment and orders.

What does chewy:reset_all do?  I didn't run that and couldn't find it.

Thank you for your help!

**Comment by linkwoman** [comment]
Oh and http://localhost:9200/ works, while http://localhost:9250/ does not (curl returns 'couldn't connect to host')

**Comment by pyromaniac** [comment]
The certificate error seems to be your local internet problem.
Try to kill ES on 9250 and start over. Try to run rake tasks one-by-one.
https://github.com/toptal/chewy#rake-tasks
https://github.com/toptal/chewy#index-manipulation

**Comment by linkwoman** [comment]
OK trying now.

**Comment by linkwoman** [comment]
Got rake tasks to run.  rake spec - 5 failures.  Connection refused

**Comment by pyromaniac** [comment]
That's definitely because ES is not started on 9250. Btw, have you reseted chewy.yml back?

**Comment by linkwoman** [comment]
yes, I did.  should I manually start es on 9250?

**Comment by linkwoman** [comment]
Actually I'm not sure how to do that.  it would be different than my normal
es... so... normally I start ES like this:
/usr/local/share/elasticsearch-1.4.2/bin/elasticsearch

**Comment by pyromaniac** [comment]
Yeah, but `rake elasticsearch:start` starts another test cluster on 9250 it is only needed to avoid pollution of the main ES cluster.

**Comment by linkwoman** [comment]
Sorry, I get this:

Starting 2 Elasticsearch nodes..sh: elasticsearch: command not found
dyld: DYLD_ environment variables being ignored because main executable
(/bin/ps) is setuid or setgid
sh: elasticsearch: command not found

[!!!] Process failed to start (see output above)

**Comment by pyromaniac** [comment]
Which OS do you have? Maybe it makes sense to symlink elasticsearch binaries somewhere in $PATH?
