### ISSUE TITLE
Elastic Search Transport Gateway Error 504

### ISSUE THREAD

**Issue by campuskart55** [toptal/chewy_example#7]
Hello, I am trying to implement this in my local host. When I am trying to run the seed I am getting this Error. I dont understand whats the problem.

Elasticsearch::Transport::Transport::Errors::GatewayTimeout: [504] 
/home/saiteja/.rvm/gems/ruby-2.2.3/gems/elasticsearch-transport-1.0.7/lib/elasticsearch/transport/transport/base.rb:132:in `__raise_transport_error'
/home/saiteja/.rvm/gems/ruby-2.2.3/gems/elasticsearch-transport-1.0.7/lib/elasticsearch/transport/transport/base.rb:224:in `perform_request'
/home/saiteja/.rvm/gems/ruby-2.2.3/gems/elasticsearch-transport-1.0.7/lib/elasticsearch/transport/transport/http/faraday.rb:20:in `perform_request'
/home/saiteja/.rvm/gems/ruby-2.2.3/gems/elasticsearch-transport-1.0.7/lib/elasticsearch/transport/client.rb:115:in `perform_request'
/home/saiteja/.rvm/gems/ruby-2.2.3/gems/elasticsearch-api-1.0.7/lib/elasticsearch/api/namespace/common.rb:21:in `perform_request'
/home/saiteja/.rvm/gems/ruby-2.2.3/gems/elasticsearch-api-1.0.7/lib/elasticsearch/api/actions/indices/exists.rb:45:in `exists'
/home/saiteja/.rvm/gems/ruby-2.2.3/gems/chewy-0.7.0/lib/chewy/index/actions.rb:15:in `exists?'
/home/saiteja/.rvm/gems/ruby-2.2.3/gems/chewy-0.7.0/lib/chewy/type/import.rb:24:in `import'
/home/saiteja/.rvm/gems/ruby-2.2.3/gems/chewy-0.7.0/lib/chewy/strategy/atomic.rb:27:in `block in leave'
/home/saiteja/.rvm/gems/ruby-2.2.3/gems/chewy-0.7.0/lib/chewy/strategy/atomic.rb:27:in `each'
/home/saiteja/.rvm/gems/ruby-2.2.3/gems/chewy-0.7.0/lib/chewy/strategy/atomic.rb:27:in `all?'
/home/saiteja/.rvm/gems/ruby-2.2.3/gems/chewy-0.7.0/lib/chewy/strategy/atomic.rb:27:in `leave'
/home/saiteja/.rvm/gems/ruby-2.2.3/gems/chewy-0.7.0/lib/chewy/strategy.rb:36:in `tap'
/home/saiteja/.rvm/gems/ruby-2.2.3/gems/chewy-0.7.0/lib/chewy/strategy.rb:36:in `pop'
/home/saiteja/.rvm/gems/ruby-2.2.3/gems/chewy-0.7.0/lib/chewy/strategy.rb:44:in `wrap'
/home/saiteja/.rvm/gems/ruby-2.2.3/gems/chewy-0.7.0/lib/chewy.rb:161:in `strategy'
/home/saiteja/chewy_example/db/seeds.rb:9:in `<top (required)>'
/home/saiteja/.rvm/gems/ruby-2.2.3/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:268:in `load'
/home/saiteja/.rvm/gems/ruby-2.2.3/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:268:in `block in load'
/home/saiteja/.rvm/gems/ruby-2.2.3/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:240:in `load_dependency'
/home/saiteja/.rvm/gems/ruby-2.2.3/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:268:in `load'
/home/saiteja/.rvm/gems/ruby-2.2.3/gems/railties-4.2.1/lib/rails/engine.rb:547:in `load_seed'
/home/saiteja/.rvm/gems/ruby-2.2.3/gems/activerecord-4.2.1/lib/active_record/tasks/database_tasks.rb:250:in `load_seed'
/home/saiteja/.rvm/gems/ruby-2.2.3/gems/activerecord-4.2.1/lib/active_record/railties/databases.rake:180:in `block (2 levels) in <top (required)>'
Tasks: TOP => db:seed

**Comment by pyromaniac** [comment]
Looks like something with ES, is it started? Restart it maybe?

**Comment by campuskart55** [comment]
It shows Elastic search cant be found ! But in Bundle list, it is installed.
